# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 668b9d7098b029d8322914fd25e48ef451956117a7dbb42455203548cb68bdec526a0aedb664a3a85d7f725e8f75fb4c373c15151c397ae85d6186e59f00eb2d

test:
  secret_key_base: ab8c78c8f963e7e37fe9a4eb841c43449b7a63ee85c6b736440c080300eb1b4512065b7987b20f1417d6535a7b206ed9073d07260157c92a65f6c1af00393273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
